[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run migrate:up && npm start"
healthcheckPath = "/ping"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[environments.production.deploy]
numReplicas = 1
